# Blog info
blog_name: Yang Yuanming
slogan: Stay hungry, stay foolish.
url: http://yangyuanming.com

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /images/favicon.ico

# For seo
keywords: Yuanming,Yang Yuanming,后台,Java Web,Java,Spring MVC,Spring,Mybatis

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Project
    url: /project/
    target_blank: false #在新页面打开
  - name: Github
    url: https://github.com/yangyuanming
    target_blank: true
  

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  #- name: 友链
  #  url: /link/
  #  target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: Go ~

link_slogan:
  isShow: false # true|fase
  text: 交换友链:yuanming.yang@qq.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 打赏
  tip: 扫一扫ヽ(ﾟ∀ﾟ)ﾒ(ﾟ∀ﾟ)ﾉ
  items:
    - type: 微信
      text: (●´∀｀●)ﾉ
      imgUrl: /images/wechatpay.png
    - type: 支付宝
      text: ﾍ(ﾟ∀ﾟﾍ)ｱﾋｬ
      imgUrl: /images/alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 

# Comment service
#disqus_shortname: forsigner
# gitalk_shortname: forsigner
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

#有言用户编号
#uyan_key:

# changyan_appid:
# changyan_appkey:

# gitment comment service
# gitment:
#     on: false  # true | false  这里开启
#     owner: # Your GitHub ID. Required.
#     repo: # The repository to store your comments. Make sure you're repo's owner. Required.
#     oauth: # An object contains your client ID and client secret. Required.
#         client_id: # GitHub client ID. Required.
#         client_secret: # GitHub client secret. Required.
#     id: # An optional string to identify your page. Default location.href.
#     title: # An optional title for your page, used as issue's title. Default document.title.
#     link: # An optional link for your page, used in issue's body. Default location.href.
#     desc: # An optional description for your page, used in issue's body. Default ''.
#     labels: # An optional array of labels your want to add when creating the issue. Default [].
#     theme: # An optional Gitment theme object. Default gitment.defaultTheme.
#     perPage: # An optional number to which comments will be paginated. Default 20.
#     maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: true # 如果使用valine，请设置改之为true
  appid: snQG2BlnuDUYlMKA3QV7n02L-gzGzoHsz # your leancloud application appid
  appkey: 74MpPI7wyUFhF7AQyckc8Uad # your leancloud application appkey
  notify: true # mail notifier , https://github.com/xCss/Valine/wiki
  verify: true # Verification code
  placeholder: 不说点什么吗……没关系，反正我也不一定看到(发email呗)ε==(づ′▽`)づ # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size

# 注意，多说即将关闭，建议选用上面四个评论系统
# duoshuo_shortname: forsigner



# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "IMIS,GDUT"
    - "喜欢听音乐、看电影，擅长编程，喜欢睡懒觉，不爱运动，死宅."
    - "后台开发工程师，常用 Spring / Spring MVC / Mybatis."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@yangyuanming"
    text_value_url: https://github.com/yangyuanming
  - type: weibo
    icon: icon-weibo
    text_key: 微博
    text_value: "@hitkoo"
    text_value_url: https://weibo.com/u/1926793802
  - type: mail
    icon: icon-mail
    text_key: Qmail
    text_value: "yuanming.yang@qq.com"
  - type: location
    icon: icon-location
    text_value: Guangzhou
#友情链接
link:
 # - name: Yuanming
 #   info: 迷途少年
 #   url: http://yym.im/
 #   avatar: http://yym.im/favcion.ico
  
#项目
project:
  - type: personal
    name: yangyuanming.github.io
    url: https://github.com/yangyuanming/yangyuanming.github.io
    intro: My Hexo Blog
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
  
